# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-23 20:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[(b'IP', b'In Pending'), (b'CH', b'Challenged'), (b'AP', b'Approved')], max_length=2)),
                ('status_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=100)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('status_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'moderation Queue',
                'verbose_name_plural': 'moderation Queue',
            },
        ),
    ]
